# Site settings
title: Raúl Chirinos
description: Web Developer
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "rjchirinos.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Raúl Chirinos
user_description:
  I am a Full Stack Web Developer from Venezuela<br>Server-side Web Development, Python and Node.js Scripting, MERN Stack projects<br>Web and App deployment, FrontEnd Experience with HTML5, CSS, JavaScript, jQuery, React.js.<br>Spanish and English speaker, Friendly personality and working compromise.<br>Also a pizza lover.
user_title: Web Developer
email: raulstuf@gmail.com
twitter_username: RaulfullCode
github_username: rjchirinos
gplus_username: lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-119787776-1"

# exclude: ['package.json', 'node_modules']
