# Site settings
title: Raúl Chirinos
description: Web Developer
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "rjchirinos.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Raúl Chirinos
user_description: I am a Backend Web Developer and Django specialist.<br>Love to build things and code for people and demogorgons sometimes.<br>I want to start my journey as Freelancer Web Developer.<br>Also love to make (and eat) pizzas and read books.
user_title: Python | Django Developer
email: raulstuf@gmail.com
twitter_username: RaulfullCode
github_username:  rjchirinos
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

# exclude: ['package.json', 'node_modules']
