# Site settings
title: Raúl Chirinos | Web Solutions for Startups and Agencies
description: Web Developer
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "rjchirinos.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Raúl Chirinos
user_description:
  I'm a Full Stack Web Developer based in Venezuela<br>Who love to work with startups, agencies and collaborate with talented people around the world<br>Building Web aplications with a wide range of technologies.
user_title: Web Developer
email: raulstuf@gmail.com
twitter_username: RaulfullCode
github_username: rjchirinos
linkedin_username: rjchirinos
gplus_username: lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-119787776-1"

# exclude: ['package.json', 'node_modules']
